# The name of your Cloudflare Worker project
name = "restate-cloudflare-worker"

# Entrypoint
main = "./src/index.ts"

# Preview URLs are used to register to Restate
preview_urls = true

# Disable minification.
# The CF Worker minifier incorrectly removes parts of the Restate SDK
minify = false

# Enable NodeJS compatibility (used by the SDK for the Node Buffer API)
compatibility_date = "2024-05-13"
compatibility_flags = [ "nodejs_compat" ]