name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAAssistant:
    uses: restatedev/restate/.github/workflows/cla.yml@main
    secrets: inherit
