packages:
  - packages/libs/*
  - packages/tests/*
  - packages/examples/*

catalog:
  zod: ^4.2.0

ignoredBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
  - workerd

onlyBuiltDependencies:
  - heapdump
