"use strict";

import { RestateContext, setContext } from "../restate_context";
import { FileDescriptorProto } from "ts-proto-descriptors";

export class GrpcServiceMethod<I, O> {
  constructor(
    readonly name: string, // the gRPC name as defined in the .proto file
    readonly localName: string, // the method name as defined in the class.
    readonly localFn: (instance: unknown, input: I) => Promise<O>, // the actual function
    readonly inputDecoder: (buf: Uint8Array) => I, // the protobuf decoder
    readonly outputEncoder: (output: O) => Uint8Array // protobuf encoder
  ) {}
}

export class GrpcService {
  constructor(
    readonly name: string,
    readonly packge: string,
    readonly impl: object,
    readonly methods: Array<GrpcServiceMethod<unknown, unknown>>
  ) {}
}

export class HostedGrpcServiceMethod<I, O> {
  /* eslint-disable @typescript-eslint/no-explicit-any */
  public reject!: (reason: any) => void;

  constructor(
    readonly instance: unknown,
    readonly service: string,
    readonly method: GrpcServiceMethod<I, O>
  ) {}

  async invoke(
    context: RestateContext,
    inBytes: Uint8Array
  ): Promise<Uint8Array> {
    return new Promise<Uint8Array>((resolve, reject) => {
      this.reject = reject;
      const instanceWithContext = setContext(this.instance, context);
      const input = this.method.inputDecoder(inBytes);
      this.method
        .localFn(instanceWithContext, input)
        .then((output) => {
          const outBytes = this.method.outputEncoder(output);
          resolve(outBytes);
        })
        .catch((error) => {
          reject(error);
        });
    });
  }
}

//
// The following definitions are equivalent to the ones
// generated by the protoc ts plugin.
// we use them to traverse the FileDescriptor
//
/* eslint-disable @typescript-eslint/no-explicit-any */
type ProtoMetaMessageOptions = {
  options?: { [key: string]: any };
  fields?: { [key: string]: { [key: string]: any } };
  oneof?: { [key: string]: { [key: string]: any } };
  nested?: { [key: string]: ProtoMetaMessageOptions };
};

export interface ProtoMetadata {
  fileDescriptor: FileDescriptorProto;
  references: { [key: string]: any };
  dependencies?: ProtoMetadata[];
  options?: {
    options?: { [key: string]: any };
    services?: {
      [key: string]: {
        options?: { [key: string]: any };
        methods?: { [key: string]: { [key: string]: any } };
      };
    };
    messages?: { [key: string]: ProtoMetaMessageOptions };
    enums?: {
      [key: string]: {
        options?: { [key: string]: any };
        values?: { [key: string]: { [key: string]: any } };
      };
    };
  };
}
