/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function registerLogCallbacks(vmLog: (...args: any[]) => any, fatal: (...args: any[]) => any): void
/**
 * Setups the native module. Kept for API parity with the WASM binding; the
 * panic hook is installed by `registerLogCallbacks`.
 */
export declare function start(): void
export const enum LogLevel {
  TRACE = 0,
  DEBUG = 1,
  INFO = 2,
  WARN = 3,
  ERROR = 4
}
/** How the state machine should behave when it hits a journal mismatch (non-determinism) error. */
export const enum WasmJournalMismatchBehavior {
  /** Follow the normal retry policy. */
  Retry = 0,
  /** Pause the invocation instead of retrying. */
  Pause = 1,
  /** Fail the invocation terminally instead of retrying. */
  Fail = 2
}
/** This will set the log level of the overall log subscriber. */
export declare function set_log_level(level: LogLevel): void
export const enum WasmCommandType {
  Input = 0,
  Output = 1,
  GetState = 2,
  GetStateKeys = 3,
  SetState = 4,
  ClearState = 5,
  ClearAllState = 6,
  GetPromise = 7,
  PeekPromise = 8,
  CompletePromise = 9,
  Sleep = 10,
  Call = 11,
  OneWayCall = 12,
  SendSignal = 13,
  Run = 14,
  AttachInvocation = 15,
  GetInvocationOutput = 16,
  CompleteAwakeable = 17,
  CancelInvocation = 18
}
/** Plain `{ key, value }` object used for header arrays in and out of the VM. */
export interface WasmHeaderData {
  key: string
  value: string
}
export interface WasmResponseHead {
  status_code: number
  headers: Array<WasmHeaderData>
}
export interface WasmFailureMetadata {
  key: string
  value: string
}
export interface WasmFailure {
  code: number
  message: string
  metadata: Array<WasmFailureMetadata>
}
/**
 * Retry config. Millisecond fields are `number` (f64) to match the WASM
 * binding's tsify representation (the VM method millis are `bigint`, but this
 * nested object uses `number`).
 */
export interface WasmExponentialRetryConfig {
  initial_interval?: number
  factor: number
  max_interval?: number
  max_attempts?: number
  max_duration?: number
}
export interface WasmAwakeable {
  id: string
  handle: number
}
export interface WasmRun {
  replayed: boolean
  handle: number
}
export interface WasmCallHandle {
  invocation_id_completion_id: number
  call_completion_id: number
}
export interface WasmSendHandle {
  invocation_id_completion_id: number
}
export interface WasmInput {
  invocation_id: string
  key: string
  idempotency_key?: string
  scope?: string
  limit_key?: string
  headers: Array<WasmHeaderData>
  input: Buffer
  random_seed: bigint
}
export declare function cancel_handle(): number
/**
 * A `key`/`value` header. Exposed as a class so the SDK can do
 * `new vm.WasmHeader(k, v)` exactly like with the WASM binding. Header arrays
 * crossing the boundary use the plain [`WasmHeaderData`] object, into which a
 * `WasmHeader` instance is structurally extracted.
 */
export declare class WasmHeader {
  key: string
  value: string
  constructor(key: string, value: string)
}
export declare class WasmVM {
  constructor(headers: Array<WasmHeaderData>, logLevel: LogLevel, loggerId: number, disablePayloadChecks: boolean, explicitCancellation: boolean, onJournalMismatch: WasmJournalMismatchBehavior)
  get_response_head(): WasmResponseHead
  notify_input(buffer: Uint8Array): void
  notify_input_closed(): void
  notify_error(errorMessage: string, stacktrace?: string | undefined | null): void
  notify_error_with_delay_override(errorMessage: string, stacktrace?: string | undefined | null, delayOverride?: bigint | undefined | null): void
  notify_error_for_next_command(errorMessage: string, stacktrace: string | undefined | null, wasmCommandType: WasmCommandType): void
  notify_error_for_specific_command(errorMessage: string, stacktrace: string | undefined | null, wasmCommandType: WasmCommandType, commandIndex: number, commandName?: string | undefined | null): void
  take_output(): Buffer
  is_ready_to_execute(): boolean
  is_completed(handle: number): boolean
  do_progress(future: any): unknown
  take_notification(handle: number): unknown
  sys_input(): WasmInput
  sys_get_state(key: string): number
  sys_get_state_keys(): number
  sys_set_state(key: string, buffer: Uint8Array): void
  sys_clear_state(key: string): void
  sys_clear_all_state(): void
  sys_sleep(millis: bigint, name?: string | undefined | null): number
  sys_attach_invocation(invocationId: string): number
  sys_get_invocation_output(invocationId: string): number
  sys_call(service: string, handler: string, buffer: Uint8Array, key: string | undefined | null, headers: Array<WasmHeaderData>, idempotencyKey?: string | undefined | null, scope?: string | undefined | null, limitKey?: string | undefined | null, name?: string | undefined | null): WasmCallHandle
  sys_send(service: string, handler: string, buffer: Uint8Array, key: string | undefined | null, headers: Array<WasmHeaderData>, delay?: bigint | undefined | null, idempotencyKey?: string | undefined | null, scope?: string | undefined | null, limitKey?: string | undefined | null, name?: string | undefined | null): WasmSendHandle
  sys_awakeable(): WasmAwakeable
  sys_complete_awakeable_success(id: string, buffer: Uint8Array): void
  sys_complete_awakeable_failure(id: string, value: WasmFailure): void
  sys_signal(signalName: string): number
  sys_complete_signal_success(invocationId: string, signalName: string, buffer: Uint8Array): void
  sys_complete_signal_failure(invocationId: string, signalName: string, value: WasmFailure): void
  sys_get_promise(key: string): number
  sys_peek_promise(key: string): number
  sys_complete_promise_success(key: string, buffer: Uint8Array): number
  sys_complete_promise_failure(key: string, value: WasmFailure): number
  sys_run(name: string): WasmRun
  propose_run_completion_success(handle: number, buffer: Uint8Array): void
  propose_run_completion_failure(handle: number, value: WasmFailure): void
  propose_run_completion_failure_transient(handle: number, errorMessage: string, errorStacktrace: string | undefined | null, attemptDuration: bigint, config?: WasmExponentialRetryConfig | undefined | null): void
  propose_run_completion_failure_transient_with_delay_override(handle: number, errorMessage: string, errorStacktrace: string | undefined | null, attemptDuration: bigint, delayOverride?: bigint | undefined | null, maxRetryAttemptsOverride?: number | undefined | null, maxRetryDurationOverride?: bigint | undefined | null): void
  propose_run_completion_failure_transient_with_pause(handle: number, errorMessage: string, errorStacktrace: string | undefined | null, attemptDuration: bigint): void
  sys_cancel_invocation(targetInvocationId: string): void
  sys_write_output_success(buffer: Uint8Array): void
  sys_write_output_failure(value: WasmFailure): void
  sys_end(): void
  is_processing(): boolean
  last_command_index(): number
}
export declare class WasmIdentityVerifier {
  constructor(keys: Array<string>)
  verify_identity(path: string, headers: Array<WasmHeaderData>): void
}
