name: Manual Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish.yml
    secrets: inherit
